name: matsci465
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0
  - aom=3.12.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlicffi=1.2.0.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - cfitsio=4.6.2
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.1
  - cpython=3.10.19
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.12.0
  - dask-core=2025.12.0
  - dask-image=2025.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.12.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - flexcache=0.3
  - flexparser=0.4
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2026.1.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - git=2.52.0
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h11=0.16.0
  - h5py=3.15.1
  - harfbuzz=10.2.0
  - hdf5=1.14.6
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperspy=2.3.0
  - hyperspy-base=2.3.0
  - hyperspy-gui-ipywidgets=2.1.0
  - hyperspy-gui-traitsui=2.1.1
  - icu=73.1
  - idna=3.11
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.31.0
  - ipympl=0.9.8
  - ipython=8.30.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jpeg=9f
  - json5=0.12.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.4
  - libavif=1.3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=20.1.8
  - libcurl=8.18.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgrpc=1.71.0
  - libiconv=1.18
  - libintl=0.25.1
  - libkrb5=1.21.3
  - libllvm20=20.1.8
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libopus=1.6
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - link-traits=1.0.3
  - llvm-openmp=20.1.8
  - llvmlite=0.44.0
  - lmdb=0.9.31
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.15.0
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numexpr=2.14.1
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=2.2.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.3
  - pandocfilters=1.5.1
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.47
  - pentapy=1.4.1
  - perl=5.32.1
  - pexpect=4.9.0
  - pillow=12.0.0
  - pims=0.7
  - pint=0.24.4
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - ply=3.11
  - pooch=1.8.2
  - prettytable=3.17.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pybaselines=1.2.1
  - pycparser=2.23
  - pyface=8.0.0
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.4
  - pysocks=1.7.1
  - python=3.10.15
  - python-box=7.3.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qt-main=5.15.2
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rosettasciio-base=0.12.0
  - rpds-py=0.28.0
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - scikit-image=0.25.2
  - scipy=1.15.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - sip=6.15.0
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.51.1
  - stack_data=0.6.3
  - sympy=1.14.0
  - tblib=3.2.2
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2024.12.12
  - tinycss2=1.4.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traits=7.1.0
  - traitsui=8.0.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.3
  - utf8proc=2.6.1
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.7
  - pip:
      - colorspacious==1.1.2
      - dill==0.4.0
      - emdfile==0.0.16
      - filelock==3.20.3
      - gdown==5.2.1
      - hdf5plugin==6.0.0
      - mpire==2.10.2
      - ncempy==1.11.1
      - numpy==1.26.4
      - py4dstem==0.14.18
      - pyaml==25.7.0
      - pylops==2.6.0
      - pyqt5-sip==12.9.0
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.2
